[log]
logtostderr = true
level = "info"
logdir = "./"


[[tunnel]]
# listen address of tunnel server
listen = "rmux://0.0.0.0:48101"
# pac rule to relay traffic, 'direct' is special channel which relay direct to remote target server
pac=[{host = ".*", channel = "direct"}]
cipher = {key="asdfqwer123456", method = "chacha20poly1305"}

[[tunnel]]
# listen address of tunnel server
listen = "ws://0.0.0.0:48103"
# pac rule to relay traffic, 'direct' is special channel which relay direct to remote target server
pac=[{host = ".*", channel = "direct"}]
cipher = {key="asdfqwer12345", method = "chacha20poly1305"}
